apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: my-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: python-newrelic
        image: py-newrelic
        ports:
        - containerPort: 5000
        - nodePort: 5000
